---
es:
  admin:
    dashboard:
      keybase: Integración con keybase
    settings:
      enable_keybase:
        desc_html: Permite a tus usuarixs comprobar su identidad por medio de keybase
        title: Habilitar la integración con keybase
      outgoing_spoilers:
        desc_html: Cuando los toots federen, agrega esta etiqueta de contenido a los toots que no tengan. Es útil si tu servidor se especializa en contenido que otros servidores desearían tener con una advertencia de contenido. Los medios también se marcarán como sensibles.
        title: Advertencia de contenido para los toots salientes
      hide_followers_count:
        desc_html: No mostrar el conteo de seguidorxs en perfiles de usuarix
        title: Ocultar conteo de seguidorxs
      show_reblogs_in_public_timelines:
        desc_html: Mostrar retoots públicos en las línea de tiempo local y pública.
        title: Mostrar retoots en líneas de tiempo públicas
      show_replies_in_public_timelines:
        desc_html: Además de auto-respuestas públicas (hilos), mostrar respuestas públicas en las línea de tiempo local y pública.
        title: Mostrar respuestas en líneas de tiempo públicas
  generic:
    use_this: Usar
  settings:
    flavours: Ediciones
  otp_authentication:
    code_hint: Ingresa el código generado por tu aplicación de autenticación para confirmar
    description_html: Si habilitas la <strong>autenticación de dos factores</strong> usando una aplicación de autenticación, se requerirá que tengas tu dispositivo a la mano al iniciar sesión, este generará un código numérico o token para que lo ingreses.
    enable: Habilitar
    instructions_html: <strong>Escanea este código QR en Authy, Google Authenticator o en otra aplicación TOTP en tu dispositivo</strong>. A partir de ahora, esa aplicación generará un código numérico o token para que lo ingreses.
    manual_instructions: "Si no puedes escanear el código QR y necesitas ingresarlo manualmente, aquí está el secreto en texto simple:"
    setup: Configurar
    wrong_code: ¡El código que ingresaste no es válido! ¿La hora del servidor y del dispositivo son correctas?
